### ISSUE TITLE
Issue with Tutorial Code

### ISSUE THREAD

**Issue by HarveyEV** [pusher-community/pusher-realtime-chat-widget#15]
I followed this http://pusher.com/tutorials/realtime_chat_widget

Receiving an error in PusherChatWidget.js at line 136"
`var imageInfo = activity.actor.image;`

Error is:
`Uncaught TypeError: Cannot read property 'actor' of undefined`

I can see in the log eveything is registering well. Just get that message when I attempt to send a message.

**Comment by HarveyEV** [comment]
In debugging the server response here is the JSON received:
`{
    "activity": {
        "id": "53a87c4883e94",
        "body": "Test 123",
        "published": "Mon, 23 Jun 2014 19:13:12 +0000",
        "type": "chat-message",
        "actor": {
            "displayName": "Mike",
            "objectType": "person",
            "image": {
                "url": "http://www.gravatar.com/avatar/c5879edaabfb9f5b496b49a82a6e472d?s=80&d=mm&r=g",
                "width": 48,
                "height": 48
            }
        }
    },
    "pusherResponse": "202 ACCEPTED\n"
}1`

Leads me to believe there is an issue parsing the JSON in the PusherChatWidget.js as the activity.actor.image is clearly defined above. I also verified the JSON in JSON Lint and it validates fine.

Maybe the trailing 1 in the response is screwing the pooch? Not sure what thats for.

**Comment by HarveyEV** [comment]
adding `dataType: 'json'` option to the ajax call solved this issue for me.

**Comment by zimbatm** [comment]
Yeah nice catch. Do you mind sending a PR with the fix ?

**Comment by HarveyEV** [comment]
Just sent.

**Comment by zimbatm** [comment]
Thanks a bunch

**Comment by HarveyEV** [comment]
Anytime. Any suggestions or examples on persisting across pages? Really would be nice..

**Comment by zimbatm** [comment]
For persistence you basically want to store the data into your own backend so you can do things like search for old messages, ...

When the page load, load the X last messages from your DB and use pusher to feed any new data live so you don't need to poll your DB. Also use the same loading mechanism when pusher reconnects so the user can catch-up on any messages that they might have missed.
Ideally your DB has message IDs so that it can be queries for all messages since ID X.

Pusher's biggest requested feature is some form of caching so that user gets the last X messages on reconnect directly from pusher. We have it in the pipeline but it's not something that is going to be delivered in the next months unfortunately.

Hope that helps, let me know if you want more details on the implementation.

Cheers,
Jonas

**Comment by HarveyEV** [comment]
Yeah. Not so simple. I made a separate window for it. Definitely sub-optimal. I will investigate the DB piece of this at some point. Thanks for the info
