### ISSUE TITLE
Pusher's client is not able to receive data after triggering (''chat_message") when using Node.js as server !

### ISSUE THREAD

**Issue by hxe-m** [pusher-community/pusher-realtime-chat-widget#24]
https://github.com/pusher/pusher-realtime-chat-widget/blob/gh-pages/src/nodejs/app.js#L69

**Comment by leggetter** [comment]
Can you please provide some debug output to show the result of the interaction with the Pusher HTTP API?

```
var socketId = null;
pusher.trigger('channel-1', 'test_event', { message: "hello world" }, socketId, function(error, request, response) {
});
```

if the `error` argument is not `null` it may identify what the problem is. Otherwise you can inspect the `response`.

The next step is to look at the [Pusher Debug Console](https://pusher.com/docs/debugging#pusher_debug_console) to check the interaction is being received by Pusher. Following that you'll want to look at the output of the [Pusher JavaScript logging](https://pusher.com/docs/debugging#pusher_logging).

**Comment by haythemkh** [comment]
Using that snippet of code, I get: error=`null`. The `Pusher Debug Console` doesn't display any incoming messages events.

My customizations:
chat.html : http://pastebin.com/qR1jCD0M
app.js : http://pastebin.com/4wsV9HBk
PusherChatWidget.js : http://pastebin.com/gDF054Xr
