### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by dprevite** [pusher-community/pusher-realtime-chat-widget#6]
The link to the demo doesn't work.

**Comment by leggetter** [comment]
The link from the README directly to the demo (PHPFog) doesn't work and the one from the tutorial page on pusher.com (AppFog) is also broken.

**Comment by samuel-queniart** [comment]
+1

**Comment by zimbatm** [comment]
Thanks. Apparently phpfog is no more so we would have to move that app. http://blog.phpfog.com/2012/11/30/saying-farewell-to-php-fog/

**Comment by leggetter** [comment]
The app was migrated to AppFog. But it appears that even the AppFog version isn't working if you use the "live side-by-side" version here:
http://pusher.com/tutorials/realtime_chat_widget

The inline version on that pages doesn't work because the `Pusher` object isn't defined when it tries to create a new instance.

**Comment by zimbatm** [comment]
Thanks @leggetter. I have fixed the inline version at least.

**Comment by leggetter** [comment]
:+1:

**Comment by robhawkes** [comment]
The chat widget demo is now available here: http://pusher.com/tutorials/realtime_chat_widget
